cors:
  originPatterns: https://localhost:8080,https://localhost:3000,https://erudio.com.br
spring:
  application:
    name: first-application-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/first_spring_boot_diih?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
  open-in-view: false
logging:
  level:
    br.com.diih: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: TRUE